name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy Heroku
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "80b8851b-0254-47c4-924b-6b1157ece1d7"
          heroku_app_name: "quick-solution-api"
          heroku_email: "20424010@student.hcmus.edu.vn"
